spring:
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: ${POSTGRES_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://localhost:8090/realms/movies_catalog/protocol/openid-connect/auth
            token-uri: http://keycloak:8090/realms/movies_catalog/protocol/openid-connect/token
            user-info-uri: http://keycloak:8090/realms/movies_catalog/protocol/openid-connect/userinfo
            jwk-set-uri: http://keycloak:8090/realms/movies_catalog/protocol/openid-connect/certs
            user-name-attribute: sub

        registration:
          keycloak:
            provider: keycloak
            client-id: movies_catalog
            client-secret: GTbDbHD7LPt1EYAzKxrcIKdXfEvXq43W
            client-name: movies_catalog
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8091/login/oauth2/code/keycloak  # Добавьте эту строку
            scope: openid, profile, email
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8090/realms/movies_catalog

keycloak:
  admin:
    url: http://keycloak:8090
    realm: movies_catalog
    client-id: app-admin
    client-secret: RwHGzwL8oud6DHrA7ibLY4YIODDsfIly

server:
  port: 8091

app:
  image:
    bucket: /app/images


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG